# Site settings
title: Ian Tabolt's Blog
email: ian@tabo.lt
description: > # this means to ignore newlines until "baseurl:"
  TODO: Write description
baseurl: "" # the subpath of your site, e.g. /blog/
basehome: ""
url: "http://iantabolt.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  iantabolt

# Build settings

markdown: redcarpet

permalink: pretty

highlighter: pygments

port: 4000

nav_pages: [
  {title: About, url: /#about},
  {title: Contact, url: /#contact},
  {title: Blog, url: /blog}]
